version: '3.9'
services:
  db:
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_DB=quantstream
      - POSTGRES_USER=quantstream
      - POSTGRES_PASSWORD=quantstream
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://quantstream:quantstream@db:5432/quantstream

volumes:
  timescaledb_data:
