"""Initial migration

Revision ID: 549237442db1
Revises: 
Create Date: 2024-07-26 23:59:11.659903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '549237442db1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klines',
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('symbol', sa.String(), nullable=False),
                    sa.Column('interval', sa.String(), nullable=False),
                    sa.Column('open', sa.Float(), nullable=True),
                    sa.Column('high', sa.Float(), nullable=True),
                    sa.Column('low', sa.Float(), nullable=True),
                    sa.Column('close', sa.Float(), nullable=True),
                    sa.Column('volume', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('timestamp', 'symbol', 'interval')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('klines')
    # ### end Alembic commands ###
